# Generated by Django 4.0.6 on 2022-10-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=250)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('town', models.CharField(blank=True, max_length=150, null=True)),
                ('suburb', models.CharField(blank=True, max_length=150, null=True)),
                ('road', models.CharField(blank=True, max_length=150, null=True)),
                ('landmark', models.CharField(blank=True, max_length=150, null=True)),
                ('centerBlock', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Center Locations',
                'verbose_name_plural': 'Center Locations',
            },
        ),
        migrations.CreateModel(
            name='CountyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Counties',
                'verbose_name_plural': 'Counties',
            },
        ),
    ]
