# Generated by Django 3.2.12 on 2022-06-18 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townsmodel',
            name='County',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='locations.countymodel'),
        ),
    ]
