# Generated by Django 4.0.6 on 2022-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_townsmodel_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisplayName', models.CharField(max_length=250)),
                ('State', models.CharField(blank=True, max_length=150, null=True)),
                ('Town', models.CharField(blank=True, max_length=150, null=True)),
                ('Suburb', models.CharField(blank=True, max_length=150, null=True)),
                ('Road', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Center Locations',
                'verbose_name_plural': 'Center Locations',
            },
        ),
    ]
