# Generated by Django 4.0.6 on 2022-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_delete_townsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerlocation',
            name='CenterBlock',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='centerlocation',
            name='Landmark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
