# Generated by Django 4.0.6 on 2022-10-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_centerlocation_centerblock_centerlocation_landmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centerlocation',
            old_name='CenterBlock',
            new_name='centerBlock',
        ),
        migrations.RenameField(
            model_name='centerlocation',
            old_name='DisplayName',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='centerlocation',
            old_name='Landmark',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='centerlocation',
            old_name='Road',
            new_name='road',
        ),
        migrations.RenameField(
            model_name='centerlocation',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='centerlocation',
            old_name='Suburb',
            new_name='suburb',
        ),
        migrations.RenameField(
            model_name='centerlocation',
            old_name='Town',
            new_name='town',
        ),
        migrations.RenameField(
            model_name='countymodel',
            old_name='Name',
            new_name='name',
        ),
    ]
