# Generated by Django 4.0.6 on 2022-10-01 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProviderID', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Providers',
                'verbose_name_plural': 'Service Providers',
                'ordering': ['TimeStamp'],
            },
        ),
    ]
