# Generated by Django 4.0.6 on 2022-10-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_townsmodel_county'),
        ('services', '0008_alter_servicerequest_options'),
        ('users', '0006_alter_customuser_locationid'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProviderServiceName', models.CharField(max_length=250)),
                ('AgeBracket', models.CharField(blank=True, choices=[('18+', '18+'), ('All', 'All'), ('10+', '10+'), ('16+', '16+')], max_length=9, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Lattitude', models.CharField(blank=True, max_length=50, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('GenderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providerGenders', to='users.gender')),
                ('LocationID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providerLocation', to='locations.townsmodel')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providerProductID', to='services.product')),
                ('ProviderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providerID', to='provider.providermodel')),
                ('workingDays', models.ManyToManyField(related_name='workingdays', to='services.workingdays')),
            ],
            options={
                'verbose_name': 'Provider Services',
                'verbose_name_plural': 'Provider Services',
                'ordering': ['TimeStamp'],
            },
        ),
    ]
