# Generated by Django 4.0.6 on 2022-10-02 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_townsmodel_county'),
        ('provider', '0002_providerservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerservice',
            name='LocationID',
        ),
        migrations.AddField(
            model_name='providerservice',
            name='CenterLocationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providerLocation', to='locations.centerlocation'),
        ),
    ]
