# Generated by Django 4.0.6 on 2022-10-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_providermodel_countyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='ServiceDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
