# Generated by Django 4.0.6 on 2022-10-21 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_centerlocation_centerblock_centerlocation_landmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0006_rename_providerservicename_providerservice_servicetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('RequestText', models.TextField(blank=True, null=True)),
                ('CenterLocationID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.centerlocation')),
                ('ProviderServiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.providerservice')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requesting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Services Requests',
                'verbose_name_plural': 'Services Requests',
                'ordering': ['TimeStamp'],
            },
        ),
        migrations.CreateModel(
            name='ServiceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResponseText', models.TextField(blank=True, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('ServiceRequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.servicerequest')),
            ],
            options={
                'verbose_name': 'Services Responses',
                'verbose_name_plural': 'Services Responses',
                'ordering': ['TimeStamp'],
            },
        ),
    ]
