# Generated by Django 4.0.6 on 2022-10-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_servicerequest_serviceresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerservice',
            options={'ordering': ['-TimeStamp'], 'verbose_name': 'Provider Services', 'verbose_name_plural': 'Provider Services'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-TimeStamp'], 'verbose_name': 'Services Requests', 'verbose_name_plural': 'Services Requests'},
        ),
        migrations.AlterModelOptions(
            name='serviceresponse',
            options={'ordering': ['-TimeStamp'], 'verbose_name': 'Services Responses', 'verbose_name_plural': 'Services Responses'},
        ),
    ]
