# Generated by Django 4.0.6 on 2022-10-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_alter_providerservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providermodel',
            options={'ordering': ['timeStamp'], 'verbose_name': 'Service Providers', 'verbose_name_plural': 'Service Providers'},
        ),
        migrations.AlterModelOptions(
            name='providerservice',
            options={'ordering': ['-timeStamp'], 'verbose_name': 'Provider Services', 'verbose_name_plural': 'Provider Services'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-timeStamp'], 'verbose_name': 'Services Requests', 'verbose_name_plural': 'Services Requests'},
        ),
        migrations.AlterModelOptions(
            name='serviceresponse',
            options={'ordering': ['-timeStamp'], 'verbose_name': 'Services Responses', 'verbose_name_plural': 'Services Responses'},
        ),
        migrations.RenameField(
            model_name='providermodel',
            old_name='CountyID',
            new_name='countyID',
        ),
        migrations.RenameField(
            model_name='providermodel',
            old_name='TimeStamp',
            new_name='timeStamp',
        ),
        migrations.RenameField(
            model_name='providermodel',
            old_name='UserID',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='providerservice',
            old_name='AgeBracket',
            new_name='ageBracket',
        ),
        migrations.RenameField(
            model_name='providerservice',
            old_name='CenterLocationID',
            new_name='centerLocationID',
        ),
        migrations.RenameField(
            model_name='providerservice',
            old_name='GenderID',
            new_name='genderID',
        ),
        migrations.RenameField(
            model_name='providerservice',
            old_name='Lattitude',
            new_name='lattitude',
        ),
        migrations.RenameField(
            model_name='providerservice',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='providerservice',
            old_name='ProductID',
            new_name='productID',
        ),
        migrations.RenameField(
            model_name='providerservice',
            old_name='ProviderID',
            new_name='providerID',
        ),
        migrations.RenameField(
            model_name='providerservice',
            old_name='ServiceDescription',
            new_name='serviceDescription',
        ),
        migrations.RenameField(
            model_name='providerservice',
            old_name='ServiceTitle',
            new_name='serviceTitle',
        ),
        migrations.RenameField(
            model_name='providerservice',
            old_name='TimeStamp',
            new_name='timeStamp',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='CenterLocationID',
            new_name='centerLocationID',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='ProviderServiceID',
            new_name='providerServiceID',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='RequestText',
            new_name='requestText',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='TimeStamp',
            new_name='timeStamp',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='UserID',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='serviceresponse',
            old_name='ResponseText',
            new_name='responseText',
        ),
        migrations.RenameField(
            model_name='serviceresponse',
            old_name='ServiceRequestID',
            new_name='serviceRequestID',
        ),
        migrations.RenameField(
            model_name='serviceresponse',
            old_name='TimeStamp',
            new_name='timeStamp',
        ),
    ]
