# Generated by Django 3.2.12 on 2022-06-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='RequestText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
