# Generated by Django 3.2.12 on 2022-06-05 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_delete_workingdays'),
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='services.productcategory'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='GenderID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GenderID', to='users.gender'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='LocationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LocationID', to='locations.townsmodel'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProductID', to='services.product'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='UserID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserID', to=settings.AUTH_USER_MODEL),
        ),
    ]
