# Generated by Django 3.2.12 on 2022-06-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220605_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='WorkingDays',
            field=models.ManyToManyField(related_name='working_days', to='services.WorkingDays'),
        ),
    ]
