# Generated by Django 3.2.12 on 2022-06-05 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('services', '0004_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='LocationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='locations.townsmodel'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='services.product'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
