# Generated by Django 4.0.6 on 2022-07-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_advertisement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'ordering': ['TimeStamp'], 'verbose_name': 'Service Providers', 'verbose_name_plural': 'Service Providers'},
        ),
    ]
