# Generated by Django 4.0.6 on 2022-10-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_remove_providerservice_locationid_and_more'),
        ('services', '0008_alter_servicerequest_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ServiceCategory',
        ),
        migrations.RemoveField(
            model_name='requestresponse',
            name='ProviderID',
        ),
        migrations.RemoveField(
            model_name='requestresponse',
            name='RequestID',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='GenderID',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='LocationID',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='ProductID',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='WorkingDays',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='LocationID',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='ProductID',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='UserID',
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.DeleteModel(
            name='RequestResponse',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
