# Generated by Django 4.0.6 on 2022-10-08 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_locationid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0006_centerlocation_centerblock_centerlocation_landmark'),
        ('services', '0010_alter_service_options_alter_servicecategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdText', models.TextField()),
                ('ExpiryDate', models.DateField()),
                ('NoOfMessages', models.IntegerField()),
                ('GenderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.gender')),
                ('LocationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.countymodel')),
                ('ServiceID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.service')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisements',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
