# Generated by Django 4.0.6 on 2022-10-08 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='StartDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='NoOfMessages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
