# Generated by Django 4.0.6 on 2022-10-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_advertisement_startdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='AdText',
            new_name='AdDescription',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ADTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='ServiceID',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ServiceID',
            field=models.ManyToManyField(blank=True, null=True, to='services.service'),
        ),
    ]
