# Generated by Django 4.0.6 on 2022-10-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_advertisement_serviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='AdDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
