# Generated by Django 4.0.6 on 2022-10-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_advertisement_userid_advertisement_providerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='AdDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='ExpiryDate',
            new_name='expiryDate',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='GenderID',
            new_name='genderID',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='LocationID',
            new_name='locationID',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='NoOfMessages',
            new_name='noOfMessages',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='ProviderID',
            new_name='providerID',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='ServiceID',
            new_name='serviceID',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='StartDate',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='ADTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='CategoryID',
            new_name='categoryID',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='Name',
            new_name='name',
        ),
    ]
