# Generated by Django 3.2.12 on 2022-06-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('MobileNumber', models.CharField(max_length=10, unique=True)),
                ('IDNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('YearOfBirth', models.DateField(blank=True, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('MiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('SurName', models.CharField(blank=True, max_length=50, null=True)),
                ('ADBalance', models.FloatField(blank=True, default=0, null=True)),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('GenderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.gender')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
