# Generated by Django 4.0.6 on 2022-07-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='IDNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
