# Generated by Django 4.0.6 on 2022-09-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_townsmodel_county'),
        ('users', '0005_alter_customuser_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='LocationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.countymodel'),
        ),
    ]
